import { Prop } from '../types';

export const textStyleProps: Record<string, Prop> = {
  color: {
    name: 'Color',
    optional: true,
    value: undefined,
    shownValue: '#000000',
    oldValue: '#000000',
    oldShownValue: '#000000',
    renderType: 'string',
    selectorType: 'colorPicker',
    selectorProps: {},
  },
  fontSize: {
    name: 'Font size',
    optional: true,
    value: undefined,
    shownValue: 14,
    oldValue: 14,
    oldShownValue: 14,
    renderType: 'number',
    selectorType: 'slider',
    selectorProps: {
      step: 1,
      minimumValue: 2,
      maximumValue: 50,
    },
  },
  fontStyle: {
    name: 'Font style',
    optional: true,
    value: undefined,
    shownValue: 'normal',
    oldValue: 'normal',
    oldShownValue: 'normal',
    renderType: 'string',
    selectorType: 'dropDown',
    selectorProps: {
      options: [
        { value: 'normal', label: 'Normal' },
        { value: 'italic', label: 'Italic' },
      ],
    },
  },
  fontWeight: {
    name: 'Font weight',
    optional: true,
    value: undefined,
    shownValue: 'normal',
    oldValue: 'normal',
    oldShownValue: 'normal',
    renderType: 'string',
    selectorType: 'dropDown',
    selectorProps: {
      options: [
        { value: 'normal', label: 'Normal' },
        { value: 'bold', label: 'Bold' },
      ],
    },
  },
  letterSpacing: {
    name: 'Letter spacing',
    optional: true,
    value: undefined,
    shownValue: 0,
    oldValue: 0,
    oldShownValue: 0,
    renderType: 'number',
    selectorType: 'slider',
    selectorProps: {
      step: 1,
      minimumValue: 0,
      maximumValue: 30,
    },
  },
  lineHeight: {
    name: 'Line height',
    optional: true,
    value: undefined,
    shownValue: 17,
    oldValue: 17,
    oldShownValue: 17,
    renderType: 'number',
    selectorType: 'slider',
    selectorProps: {
      step: 1,
      minimumValue: 8,
      maximumValue: 100,
    },
  },
  textAlign: {
    name: 'Text align',
    optional: true,
    value: undefined,
    shownValue: 'auto',
    oldValue: 'auto',
    oldShownValue: 'auto',
    renderType: 'string',
    selectorType: 'dropDown',
    selectorProps: {
      options: [
        { value: 'auto', label: 'Auto' },
        { value: 'left', label: 'Left' },
        { value: 'right', label: 'Right' },
        { value: 'center', label: 'Center' },
        { value: 'justify', label: 'Justify' },
      ],
    },
  },
  textDecorationLine: {
    name: 'Text decoration line',
    optional: true,
    value: undefined,
    shownValue: 'none',
    oldValue: 'none',
    oldShownValue: 'none',
    renderType: 'string',
    selectorType: 'dropDown',
    selectorProps: {
      options: [
        { value: 'none', label: 'None' },
        { value: 'underline', label: 'Underline' },
        { value: 'line-through', label: 'Line-through' },
        { value: 'underline line-through', label: 'Underline & line-through' },
      ],
    },
  },
  textShadowColor: {
    name: 'Text shadow color',
    optional: true,
    value: undefined,
    shownValue: '#000000',
    oldValue: '#000000',
    oldShownValue: '#000000',
    renderType: 'string',
    selectorType: 'colorPicker',
    selectorProps: {},
  },
  textShadowOffset: {
    name: 'Text shadow offset',
    subprops: {
      width: {
        name: 'Width',
        optional: true,
        value: undefined,
        shownValue: 0,
        oldValue: 0,
        oldShownValue: 0,
        renderType: 'number',
        selectorType: 'slider',
        selectorProps: {
          step: 1,
          minimumValue: 0,
          maximumValue: 50,
        },
      },
      height: {
        name: 'Height',
        optional: true,
        value: undefined,
        shownValue: 0,
        oldValue: 0,
        oldShownValue: 0,
        renderType: 'number',
        selectorType: 'slider',
        selectorProps: {
          step: 1,
          minimumValue: 0,
          maximumValue: 50,
        },
      },
    },
  },
  textShadowRadius: {
    name: 'Text shadow radius',
    optional: true,
    value: undefined,
    shownValue: 0,
    oldValue: 0,
    oldShownValue: 0,
    renderType: 'number',
    selectorType: 'slider',
    selectorProps: {
      step: 1,
      minimumValue: 0,
      maximumValue: 10,
    },
  },
  textTransform: {
    name: 'Text transform',
    optional: true,
    value: undefined,
    shownValue: 'none',
    oldValue: 'none',
    oldShownValue: 'none',
    renderType: 'string',
    selectorType: 'dropDown',
    selectorProps: {
      options: [
        { value: 'none', label: 'None' },
        { value: 'uppercase', label: 'Uppercase' },
        { value: 'lowercase', label: 'Lowercase' },
        { value: 'capitalize', label: 'Capitalize' },
      ],
    },
  },
};
